[package]
name = "ibackuptools2"
version = "0.1.0"
authors = ["Rich Infante <rich@richinfante.com>"]
edition = "2018"

[dependencies]
rusqlite = "0.17.0"
plist = "0.4.1"
dirs = "1.0.5"
rust-crypto = "^0.2"
colored = "1.7"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.10.5"